### ISSUE TITLE
Update UI

### ISSUE THREAD

**Issue by FutureProg** [teovoinea/podium#73]
### Task
Update the UI to match the [Figma designs](https://www.figma.com/file/FJ2bx4EHAVzsZAkP94WR2s/Podium?node-id=14%3A1). 

### Requirements

- match the colour scheme, layout, and font styles of the redesigned UI

**Comment by teovoinea** [comment]
Broke this up into 2:
1. Update the styles to match the figma designs (this issue)
2. Add light mode colours #149

**Comment by teovoinea** [comment]
https://user-images.githubusercontent.com/8150726/111398336-89287d00-8680-11eb-848a-a5d95914676a.mov

@FutureProg What do you think of this?
