### ISSUE TITLE
Store file location when indexing files

### ISSUE THREAD

**Issue by teovoinea** [teovoinea/podium#75]
Today, most indexers don't capture file locations. It's an expectation that users can search based on file name.

In most indexers you will see code like this:
https://github.com/teovoinea/podium/blob/389dda4201dabb03af6d915678af96dfea4ea54e/src/indexers/spreadsheet_indexer.rs#L60-L63

We want to capture the file path in `DocumentSchema.name`. You can find the file path in `file_to_process.path`.

This can be done like this
```rust
 Ok(DocumentSchema { 
     name: file_to_process.path.file_name().unwrap().to_string_lossy().to_string(), 
     body: strings, 
 })
```

List of indexers to update:

- [x] csv_indexer #76 
- [x] exif_indexer #77 
- [x] mobile_net_v2_indexer #78 
- [x] pdf_indexer #79 
- [x] spreadsheet_indexer #80

**Comment by devzbysiu** [comment]
mobile_net_v2_indexer part addressed here: https://github.com/teovoinea/podium/pull/86
